admin:
  resource: ../src/Controller/Admin/*.php
  prefix: /admin
  name_prefix: admin_
  type: annotation

restaurateur:
  resource: ../src/Controller/Restaurateur/*.php
  prefix: /restaurateur
  name_prefix: restaurateur_
  type: annotation

home:
  path: /
  controller: App\Controller\IndexController::accueil
  defaults:
      path: /accueil
      permanent: true