admin:
  resource: ../src/Controller/Admin/*.php
  prefix: /admin
  name_prefix: admin_
  type: annotation

restaurateur:
  resource: ../src/Controller/Restaurateur/*.php
  prefix: /restaurateur
  name_prefix: restaurateur_
  type: annotation