twig:
    globals:
        delivery_price: '%env(DELIVERY_PRICE)%'
        
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null

